# Generated by Django 3.2.9 on 2024-05-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egitmenler',
            fields=[
                ('egitmenID', models.AutoField(primary_key=True, serialize=False)),
                ('egitmenTamAd', models.CharField(max_length=50)),
                ('egitmenEposta', models.CharField(max_length=50)),
                ('egitmenSifre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kurumlar',
            fields=[
                ('kurumID', models.AutoField(primary_key=True, serialize=False)),
                ('kurumAdi', models.CharField(max_length=50)),
                ('kurumWebsite', models.CharField(max_length=50)),
                ('kurumEposta', models.CharField(max_length=50)),
                ('kurumSifre', models.CharField(max_length=50)),
                ('kurumPaketSonTarih', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Paketler',
            fields=[
                ('paketID', models.AutoField(primary_key=True, serialize=False)),
                ('paketAdi', models.CharField(max_length=50)),
                ('paketFiyat', models.FloatField()),
                ('paketMaxKullanici', models.IntegerField()),
                ('paketAciklama', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Yoneticiler',
            fields=[
                ('yoneticiID', models.AutoField(primary_key=True, serialize=False)),
                ('yoneticiEmail', models.CharField(max_length=70)),
                ('yoneticiSifre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Siniflar',
            fields=[
                ('sinifID', models.AutoField(primary_key=True, serialize=False)),
                ('sinifAdi', models.CharField(max_length=50)),
                ('sinifEgitmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.egitmenler')),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenciler',
            fields=[
                ('ogrenciID', models.AutoField(primary_key=True, serialize=False)),
                ('ogrenciTamAd', models.CharField(max_length=50)),
                ('ogrenciFoto', models.CharField(max_length=60)),
                ('ogrenciEposta', models.CharField(max_length=50)),
                ('ogrenciSifre', models.CharField(max_length=50)),
                ('ogrenciKurum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.kurumlar')),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci_Sinif',
            fields=[
                ('osID', models.AutoField(primary_key=True, serialize=False)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.ogrenciler')),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.siniflar')),
            ],
        ),
        migrations.AddField(
            model_name='kurumlar',
            name='kurumPaket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.paketler'),
        ),
        migrations.CreateModel(
            name='Icerikler',
            fields=[
                ('icerikID', models.AutoField(primary_key=True, serialize=False)),
                ('icerikAdi', models.CharField(max_length=50)),
                ('icerikVideo', models.CharField(max_length=50)),
                ('icerikPdf', models.CharField(max_length=50)),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.siniflar')),
            ],
        ),
        migrations.AddField(
            model_name='egitmenler',
            name='egitmenKurum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.kurumlar'),
        ),
    ]
