# Generated by Django 3.2.9 on 2024-06-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_kurumlar_kurumaktif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('subtitle_file', models.FileField(blank=True, null=True, upload_to='subtitles/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='egitmenler',
            name='egitmenEposta',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='egitmenler',
            name='egitmenSifre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='egitmenler',
            name='egitmenTamAd',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kurumlar',
            name='kurumAdi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kurumlar',
            name='kurumEposta',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='kurumlar',
            name='kurumPaket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.paketler'),
        ),
        migrations.AlterField(
            model_name='kurumlar',
            name='kurumSifre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kurumlar',
            name='kurumWebsite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
